version: '3.1'
services:
  redmine:
    image: redmine:3.4
    container_name: redmine-dev
    ports:
      - 8888:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: dev-password
      RAILS_ENV: development
    volumes:
      - ../:/usr/src/redmine/plugins/redmine_httpheader_auth/
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: redmine-dev-db
    environment:
      MYSQL_ROOT_PASSWORD: dev-password
      MYSQL_DATABASE: redmine
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
